# Source: helloworld-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-helloworld-chart
  labels:
    app: helloworld-chart
    chart: helloworld-chart-0.1.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: helloworld-chart
    release: RELEASE-NAME