---
# Source: helloworld-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-helloworld-chart
  labels:
    app: helloworld-chart
    chart: helloworld-chart-0.1.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: helloworld-chart
    release: RELEASE-NAME
---
# Source: helloworld-chart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-helloworld-chart
  labels:
    app: helloworld-chart
    chart: helloworld-chart-0.1.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-chart
        release: RELEASE-NAME
    spec:
      containers:
        - name: helloworld-chart
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {}
